# Stage 1: Building the React application
FROM node:14 as build

# Setting up working directory
WORKDIR /app

# Copying package.json and package-lock.json
COPY package*.json ./

# Installing dependencies
RUN npm install

# Copy app source
COPY . .

# Build the app
RUN npm run build

# Stage 2: Serving the React application with Nginx
FROM nginx:alpine

# Copy built app to Nginx public directory
COPY --from=build /app/build /usr/share/nginx/html

# Copy nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Command to run Nginx
CMD ["nginx", "-g", "daemon off;"]
